### ISSUE TITLE
Should also work for .yml extension

### ISSUE THREAD

**Issue by adamvoss** [json-schema-everywhere/pajv#3]
_From @schickling on August 17, 2017 20:20_

Most people save the YAML files with `.yml`. Would be great if `any-json` could work with both `.yaml` and `.yml`.

_Copied from original issue: any-json/any-json#9_

**Comment by adamvoss** [comment]
What version of `any-json` are you using and what is the command are you running?

I tried to cover this case with 2b50ce5cd5948ec2a9c8708b5a6e5fcc1dcea58b which released in `3.0.0`, but I may have missed something.

**Comment by adamvoss** [comment]
_From @schickling on August 18, 2017 12:21_

I'm using the `pajv` CLI.

**Comment by adamvoss** [comment]
Should be fixed in the just released `1.2.0`

**Comment by schickling** [comment]
Fantastic :)
